// migrate.ts — Applies pending SQL migrations to the database.
// Reads migration files generated by `drizzle-kit generate` from the
// migrations/ folder and runs any that haven't been applied yet.
// Drizzle tracks applied migrations in a __drizzle_migrations table
// inside the database itself, so this is safe to run on every deployment.
//
// Usage: tsx src/db/migrate.ts
// (called automatically during deployment before the server starts)

import { migrate } from "drizzle-orm/better-sqlite3/migrator"; // external: Drizzle migration runner
import { db } from "./client.js";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// __dirname is not available in ES modules, so we reconstruct it from
// import.meta.url — the URL of this file at runtime.
const __dirname = dirname(fileURLToPath(import.meta.url));

// Run all pending migrations found in the migrations/ subdirectory.
// Migrations are applied in filename order and each runs inside a transaction.
migrate(db, { migrationsFolder: join(__dirname, "migrations") }); // reads *.sql files from disk

console.log("Migrations applied.");
